M48
; DRILL file KiCad 10.0.6 date 2026-09-15T09:33:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-15T09:33:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.950
%
G90
G05
T1
X36.295Y-12.41
X36.295Y-18.19
T2
X2.0Y-38.2
X40.0Y-38.2
T3
X11.475Y-28.0
X30.525Y-28.0
M30
