M48
; DRILL file KiCad 10.0.6 date 2026-09-24T20:55:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-24T20:55:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.950
%
G90
G05
T1
X36.295Y-24.11
X36.295Y-29.89
T2
X2.5Y-2.5
X2.5Y-52.0
X39.5Y-2.5
X39.5Y-52.0
T3
X11.475Y-40.8
X30.525Y-40.8
M30
