M48
; DRILL file KiCad 10.0.6 date 2026-09-15T06:51:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-15T06:51:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X36.295Y-10.41
X36.295Y-16.19
T2
X6.395Y-28.0
X16.555Y-28.0
X25.445Y-28.0
X35.605Y-28.0
T3
X2.5Y-37.5
X39.5Y-37.5
T4
X11.475Y-28.0
X30.525Y-28.0
M30
